Repository npdarrington/fitlit, pull requests merged in 2020-08, with the labels that each got.

#49 User repo test tj
  src/userRepo.js
  test/userRepoTest.js
  test/userTestData.js
Labels: Test Driven Development, iteration1

#50 Nd user dashboard
  src/css/normalize.css
  src/css/styles.css
  src/index.html
  src/scripts.js
  src/userRepo.js
  test/User-test.js
  test/userRepoTest.js
Labels: Dom, enhancement, iteration1

#51 Hydration dom tj
  src/Hydration.js
  src/index.html
  src/scripts.js
  test/hydration-test.js
  test/hydrationTestData.js
Labels: Dom, enhancement, iteration2

#52 Nd sleep class
  src/Sleep.js
  test/Sleep-test.js
  test/sleepTestData.js
Labels: Test Driven Development, dataset, enhancement, iteration3

#53 Nd sleep dom
  src/Hydration.js
  src/index.html
  src/scripts.js
Labels: Dom, enhancement, iteration3

#54 Iteration4 classes tests tj
  src/Activity.js
  test/activity-test-data.js
  test/activity-test.js
Labels: Dom, enhancement, iteration4

#56 Iteration 4 dom tj
  src/Activity.js
  src/index.html
  src/scripts.js
  test/activity-test.js
Labels: Dom, enhancement, iteration4

#57 Nd refactor
  src/Hydration.js
  src/Sleep.js
  src/userRepo.js
  test/Sleep-test.js
  test/activity-test-data.js
  test/hydration-test.js
  test/hydrationTestData.js
  test/userRepoTest.js
Labels: DRY, Refactor, dataset, enhancement

#58 Iteration 5 tj
  src/Activity.js
  src/index.html
  src/scripts.js
Labels: Dom, iteration5

#60 Activity refactor tj
  src/Activity.js
  src/scripts.js
  src/userRepo.js
  test/activity-test.js
Labels: DRY, Refactor

#62 Nd design ui
  src/css/styles.css
  src/images/activity.png
  src/images/calendar.png
  src/images/chat.png
  src/images/notification.png
  src/images/question.png
  src/images/resume.png
  src/images/settings.png
  src/images/sleep.png
  src/images/user.png
  src/images/water.png
  src/index.html
Labels: CSS, HTML, enhancement
